blog/urls.py
#coding: utf:8
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('',
                url(r'^$', views.Posts.as_view(), name="index"),
                url(r'^post/(?P<pk>\d+)/$',
                    views.PostDetailView.as_view(), name="pt_detail"),
         )

magazine/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls \
  import staticfiles_urlpatterns 


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'', include("blog.urls", namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
) 

urlpatterns += staticfiles_urlpatterns()

# At the top of your urls.py file, add the following line:


# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

blog/models.py
#coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse
from ckeditor.fields import RichTextField


class AbstractDate(models.Model):
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
    

class AbstractTitleData(AbstractDate):
    title = models.CharField(max_length=200)

    class Meta:
        abstract = True

   
class Category(models.Model):
    title = models.CharField(max_length=60, unique=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/{0}".format(self.title).lower()
    

class Post(AbstractTitleData):
    body = RichTextField(config_name='default')
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    category = models.ForeignKey(Category)

    def thumbnail(self):
        return """<a href="/media/%s"><img border="0" alt=""
                  src="/media/%s" height="60" /></a>""" % ((self.picture.name, self.picture.name))
    thumbnail.allow_tags = True

    class Meta:
        ordering = ["-created"]

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        #return "/post/{0}".format(self.id)
        return reverse("blog:pt_detail", kwargs={"pk": self.pk})
        


class Tag(models.Model):
    slug = models.SlugField(max_length=15)
    post = models.ManyToManyField(Post, related_name="tags")

    def __unicode__(self):
        return self.slug


class Comment(AbstractDate):
    post = models.ForeignKey(Post, related_name="comments")
    author = models.CharField(max_length=25)
    body = models.TextField()

blog/views.py
# Create your views here.
#coding: utf-8
from django.views.generic import ListView, DetailView
from blog.models import Post, Category


class CommentTagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(CommentTagMixin,
                        self).get_context_data(**kwargs)
        context["comments"] = Comment.objects.\
          filter(post=self.object)
        return context


class CategoryMixin(object):
    def get_context_data(self, **kwargs):
        context = super(CategoryMixin,
                        self).get_context_data(**kwargs)
        context["categories"] = self.categories
        return context

class Posts(CategoryMixin, ListView):
    """
    Список всех доступных статей
    """

    # Нижеуказанные параметры можно также передать данному отображению через метод as_view()
    # url(r'^$', Posts.as_view(context_object_name='posts', template_name='posts.html))
    model = Post
    # Под данным именем наш список статей будет доступен в шаблоне
    context_object_name = 'post_list'
    # Название шаблона
    template_name = 'blog/index.html'
    # Количество объектов на 1 страницу
    paginate_by = 5

    def get_queryset(self):
        queryset = self.model.objects.all().\
          prefetch_related('tags')
        self.categories = Category.objects.all()
        return queryset


class PostDetailView(CategoryMixin, DetailView):
    model = Post
    template_name = 'blog/post.html'
    queryset = Post.objects.all().\
      prefetch_related('tags')

    def get_object(self):
        self.categories = Category.objects.all()
        obj = super(PostDetailView,
                    self).get_object()
        return obj 
        
        
         

templates/blog/base.html
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Wallpoet' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href="{{ STATIC_URL }}/blog/www/css/styles.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="wrapper container-fluid">
      <div class=" row">
	<div class="col-md-12 header">
	
	  <div class="col-md-3 " id="imagine">
	    <div class="row">
	      <a href="/home/"><img class="center-block"  src="/static/blog/www/images/cologo.jpeg" ></a>
	    </div>
	  </div>

	</div> <!--col-md-12 header-->
      
      </div>
      
{% include 'blog/navbar.html' %}
      
	
    <div class="col-md-12 line-widget">
      <div class="row">
	<div class="col-xs-12 col-sm-3 col-md-3" id="greenline"> 
	  <p>FhHFHFH</p>
	</div>
	<div class="col-xs-12  col-sm-9 col-md-9" id="blackline"> 
	  <p>FhHFHFH</p>
	</div>
      </div><!-- row -->
    </div> <!-- col-md-12 line-widget -->
	
    <div class="col-md-8 block">
	  <div class="border"> </div>
	  <div class="row">
	    <div class="col-md-12 blogs">
	      <div class="row">
		   <div class="blog-category col-md-12">
		     
		     {% block post %} {% endblock %}
		     </div>
		 </div>
	      </div> <!-- col-md-12 blogs -->
	      
	
	  </div>
    </div> <!--col-md-8-block-->
   
      
      <div class="clearfix visible-xs"></div>
      

      <div class="row">
	<footer class="col-md-12">
	  <!-- Standard button -->
<button type="button" class="btn btn-default">Default</button>

<!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
<button type="button" class="btn btn-primary">Primary</button>

<!-- Indicates a successful or positive action -->
<button type="button" class="btn btn-success">Success</button>

<!-- Contextual button for informational alert messages -->
<button type="button" class="btn btn-info">Info</button>

<!-- Indicates caution should be taken with this action -->
<button type="button" class="btn btn-warning">Warning</button>

<!-- Indicates a dangerous or potentially negative action -->
<button type="button" class="btn btn-danger">Danger</button>

<!-- Deemphasize a button by making it look like a link while maintaining button behavior -->
<button type="button" class="btn btn-link">Link</button>
	</footer>
	
	
    </div>
    
    







    </div> <!-- container -->

    


















<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    
    <script src="{{STATIC_URL}}/blog/www/js/bootstrap.js"></script>
    <script src="{{STATIC_URL}}/blog/www/js/plugin.js"></script>
    
  </body>
</html>

templates/blog/index.html
{% extends 'blog/base.html' %}



{% block post %}

<h1> <small>ПОСЛЕДНИЕ ПОСТЫ</small></h1>
{% for post in post_list %}
 <div class="post">
   <div class="row">
     
     <div class="category col-md-12">
     
       <div class="cat col-md-2 col-sm-2 col-xs-4 pull-left">
	 <p class="pull-left">{{post.category}}</p> 
       </div>

       <div class="col-md-3 col-sm-3 col-xs-4 time">
	 <h4 class="pull-left"><small>{{ post.created|date:"M d, Y" }}</small></h4> 
       </div>
			 
       <div class="col-md-2 col-sm-2 col-xs-4 pull-right share">
	 <p class="pull-right">SHARE</p> 
       </div>
			 
       <div class="clearfix visible-md"></div>
     </div>
			 



     <div class="col-md-12" id="qwe">
       <h3><a href="{{post.get_absolute_url}}">{{ post.title }}</a></h3>

       <div class="post_body" id="abs">
	 {{ post.body|safe|truncatewords_html:"25"}}

	 <a href="{{ post.get_absolute_url }}">read more</a>

       </div>
       
       
       <img src="/media/{{post.picture.name}}" class="img-thumbnail" alt="Responsive image">


       <p> Tags: 
       {% for tag in post.tags.all %}
	 <a href="{{post.get_absolute_url}}">{{ tag }}</a>
	 {% if not forloop.last %}
	 |
	 {% endif %}
	 
	   {% endfor %} </p>
     </div>
   </div>
 </div> <!-- post -->
		     
{% endfor %}






{% endblock %}

templates/blog/navbar.html
    <div class="naver row">
	
     <nav class="navbar navbar-default" id="navbar " >
       
       <ul class="nav navbar-nav">
         <li class="hidden-sm hidden-xs"><a href="{% url 'blog:index'%}">Home</a></li>
  {% if categories.count > 1  %}       
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
          <ul class="dropdown-menu">
	    {% for category in categories %}
            <li><a href="{{category.get_absolute_url}}">{{category.title}}</a></li>
	    {% endfor %}
            <li><a href="#">Абусик</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
	 {% else %}


	  <li class="hidden-sm hidden-xs"><a href="/admin/">Services</a></li>


{% endif %}



	 <li class="hidden-sm hidden-xs"><a href="/admin/">Services</a></li>
         <li><a href="/partners/">Partners</a></li>
         <li><a href="/customers/">Customers</a></li>
         <li><a href="/projects/">Projects</a></li>
         <li><a href="/careers/">Careers</a></li>
         <li><a href="/contact/">Contact</a></li>			
       </ul> 
     </nav>
     
     </div> <!-- naver row --->

templates/blog/post.html
{% extends 'blog/base.html' %}

{% block post %}


 <div class="post">
   <div class="row">
     <div class="category col-md-12" id="post">
      <div class="cat col-md-2 col-sm-4 col-xs-4 pull-left">
	 <p class="pull-left">{{post.category}}</p> 
       </div>
       
      <div class="col-md-3 col-sm-4 col-xs-4 time">
	 <h4><small>{{ post.created|date:" M d, Y" }}</small></h4> 
       </div>
			 
     <div class="col-md-2 col-sm-4 col-xs-4 pull-right share">
       <p class="pull-right">SHARE</p> 
     </div>
     
     
    
			 
     <div class="clearfix visible-md"></div>
     </div>
      
			 



     <div class="col-md-12" >
       <div class="row">
       <div class="col-md-12" id="title">
       <h3><a href="{{post.get_absolute_url}}">{{ post.title }}</a></h3>
       </div>
       </div>
        <img src="/media/{{post.picture.name}}" class="img-thumbnail" alt="Responsive image">
       <p>{{ post.body|safe }} </p>
       
       
       

      <p> Tags: 
       {% for tag in post.tags.all %}
	 <a href="{{post.get_absolute_url}}">{{ tag }}</a>
	 {% if not forloop.last %}
	 |
	 {% endif %}
	 
	   {% endfor %} </p>

     </div>
   </div>
 </div>
{% endblock %}